# Command delay
cooldown:
  enabled: true
  # time in s
  time: 60

# Choose a storage system (mysql or yaml)
storage-system: yaml

mysql:
  host: "localhost"
  port: 3306
  database: vitalmail
  username: "vitalmail"
  password: ""
  prefix: "server_"